### ISSUE TITLE
Arduino library import no longer works

### ISSUE THREAD

**Issue by macegr** [plasticrake/OpcServer#2]
All the Platform.io-specific stuff seems to interfering with a regular Arduino IDE install. It will complain about incorrect characters in the library name. The 1.0 version can be partially installed, but Arduino will pop up an error every time the library manager is opened. Attempting to include the library will drop five different *.h files into your sketch, such as "Config.h" and "Platforms.h".

**Comment by plasticrake** [comment]
Arduino library issue was fixed on the library side. The extraneous *.h files are a limitation of the Arduino IDE. I've seen other libraries such as FastLED or some of Adafruit's for example have additional header files that get included. The IDE does not provide a way to ignore them.
